# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_user_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='temp',
        ),
    ]
